Repository HMuraja/happiness-unleashed, pull requests merged in 2024-03, with the labels that each got.

#18 Stephen initial setup
  .gitignore
  db.sqlite3
  happiness_project/settings.py
Labels: Must Have, Stephen

#21 Add profile app
  happiness_app/templates/happiness_app/index.html
  happiness_app/views.py
  happiness_project/settings.py
  happiness_project/urls.py
  profiles/__init__.py
  profiles/admin.py
  profiles/apps.py
  profiles/forms.py
  profiles/migrations/0001_initial.py
  profiles/migrations/__init__.py
  profiles/models.py
  profiles/static/profiles/css/profile.css
  profiles/templates/profiles/profile.html
  profiles/tests.py
  profiles/urls.py
  profiles/views.py
  static/css/base.css
  static/js/script.js
  templates/base.html
Labels: Should Have, Stephen

#22 feat: add confirmation step
  happiness_project/settings.py
  profiles/templates/profiles/profile.html
  profiles/views.py
  static/js/script.js
  templates/base.html
Labels: Should Have, Stephen

#23 feat: add dark mode toggle
  static/js/script.js
  templates/base.html
Labels: Could Have, Stephen

#25 Create acts_of_kindness app, incl models, views and templates
  .gitignore
  .gitpod.yml
  acts_of_kindness/__init__.py
  acts_of_kindness/admin.py
  acts_of_kindness/apps.py
  acts_of_kindness/fixtures/acts.json
  acts_of_kindness/forms.py
  acts_of_kindness/migrations/0001_initial.py
  acts_of_kindness/migrations/0002_actsofkindness_approved.py
  acts_of_kindness/migrations/__init__.py
  acts_of_kindness/models.py
  acts_of_kindness/static/acts_of_kindness/css/acts_of_kindness.css
  acts_of_kindness/templates/acts_of_kindness/act_detail.html
  acts_of_kindness/templates/acts_of_kindness/acts_list.html
  acts_of_kindness/templates/acts_of_kindness/add_act.html
  acts_of_kindness/templates/acts_of_kindness/edit_act.html
  acts_of_kindness/tests.py
  acts_of_kindness/urls.py
  acts_of_kindness/views.py
  happiness_project/settings.py
  happiness_project/urls.py
  requirements.txt
Labels: Must Have, Ann

#26 feat: add initial landing page
  happiness_app/templates/happiness_app/index.html
  happiness_app/views.py
  static/css/base.css
  templates/base.html
Labels: Must Have, Stephen

#34 Add landing page
  happiness_app/static/happiness_app/css/style.css
  happiness_app/templates/happiness_app/index.html
  happiness_app/views.py
  templates/base.html
Labels: Stephen

#35 User posting app
  happiness_project/settings.py
  happiness_project/urls.py
  post/__init__.py
  post/admin.py
  post/apps.py
  post/forms.py
  post/migrations/0001_initial.py
  post/migrations/__init__.py
  post/models.py
  post/static/post/css/post.css
  post/templates/post/add_post.html
  post/templates/post/edit_post.html
  post/templates/post/post_detail.html
  post/templates/post/post_list.html
  post/tests.py
  post/urls.py
  post/views.py
  templates/base.html
Labels: Should Have, Stephen

#39 Update navbar, footer,
  happiness_app/views.py
  static/css/homePage.css
  static/images/HULogo.png
  static/images/HUfavicon.ico
  static/images/user-image-hu.png
  templates/base.html
Labels: Must Have

#50 Add bulk approve functionality
  acts_of_kindness/admin.py
  acts_of_kindness/views.py
  happiness_app/views.py
Labels: Stephen

#67 Branch fl0 w
  .devcontainer/images_README/app_structure.PNG
  .devcontainer/images_README/wireframe.PNG
  .devcontainer/images_README/wireframe1.PNG
  .devcontainer/images_README/wireframe2.PNG
  README.md
  acts_of_kindness/fixtures/acts.json
  acts_of_kindness/fixtures/acts_Ann.json
Labels: Florian

#65 user can post there completed act if they want to
  acts_of_kindness/templates/acts_of_kindness/act_detail.html
  acts_of_kindness/urls.py
  acts_of_kindness/views.py
  happiness_project/settings.py
  post/views.py
  profiles/templates/profiles/profile.html
  profiles/views.py
Labels: Ann

#75 Update post forms styling
  acts_of_kindness/fixtures/acts.json
  happiness_app/templates/happiness_app/our_team.html
  happiness_app/urls.py
  happiness_app/views.py
  happiness_project/urls.py
  post/forms.py
  post/static/post/css/post.css
  post/templates/post/add_post.html
  profiles/templates/profiles/profile.html
  static/css/base.css
Labels: Should Have, Stephen

#77 adjust README.md
  README.md
  images_README/app_structure.PNG
  images_README/wireframe.PNG
  images_README/wireframe1.PNG
  images_README/wireframe2.PNG
Labels: Florian

#80 add 6 further profile cards to ourteam subpage
  happiness_app/templates/happiness_app/our_team.html
  happiness_project/settings.py
Labels: Should Have

#82 Add posts link to navbar
  templates/base.html
Labels: Must Have

#88 fix: update login id and name
  templates/account/login.html
Labels: Must Have

#84 add urls Ann
  happiness_app/templates/happiness_app/our_team.html
Labels: Should Have

#90 fix: add login form errors
  templates/account/login.html
  templates/account/signup.html
Labels: Should Have, Stephen

#83 Acts cards horizontal scrolling
  happiness_app/templates/happiness_app/index.html
  static/css/base.css
  static/css/homePage.css
  static/css/index.css
  static/js/script.js
  templates/base.html
Labels: Must Have

#99 fix: remove extra nav elements
  happiness_app/templates/happiness_app/index.html
Labels: Should Have

#97 fix: remove extra closing tag
  post/templates/post/post_list.html
Labels: Must Have, Stephen

#98 Edit the layout of Post page
  post/static/post/css/masonry.css
  post/templates/post/post_list.html
Labels: Must Have

#95 Ourteam urls
  happiness_app/static/happiness_app/css/teampage_about.css
  happiness_app/templates/happiness_app/about.html
  happiness_app/templates/happiness_app/our_team.html
  happiness_app/urls.py
  happiness_app/views.py
Labels: Florian

#101 Profile page layout
  profiles/static/profiles/css/profile.css
  profiles/templates/profiles/profile.html
Labels: Should Have

#108 Edit post details layout
  post/templates/post/post_detail.html
Labels: Must Have

#112 set debug to false
  happiness_app/templates/happiness_app/index.html
  happiness_project/settings.py
  requirements.txt
  static/css/index.css
Labels: Must Have, Stephen

#114 feat: add aok to edit post page
  post/templates/post/edit_post.html
  post/views.py
Labels: Should Have, Stephen

#110 Edit Add and Edit act of kindness details
  acts_of_kindness/templates/acts_of_kindness/add_act.html
  acts_of_kindness/templates/acts_of_kindness/edit_act.html
  post/templates/post/post_detail.html
Labels: Must Have

#122 Numerous smaller changes
  acts_of_kindness/static/acts_of_kindness/css/acts_of_kindness.css
  acts_of_kindness/templates/acts_of_kindness/acts_list.html
  happiness_app/static/happiness_app/css/teampage_about.css
  happiness_app/templates/happiness_app/about.html
  happiness_app/templates/happiness_app/index.html
  happiness_app/templates/happiness_app/our_team.html
  post/templates/post/add_post.html
  post/templates/post/edit_post.html
  profiles/templates/profiles/profile.html
  static/css/base.css
  templates/base.html
Labels: Should Have

#123 Add emails
  acts_of_kindness/templates/acts_of_kindness/act_detail.html
  acts_of_kindness/templates/acts_of_kindness/confirmation_emails/confirmation_email_body.txt
  acts_of_kindness/templates/acts_of_kindness/confirmation_emails/confirmation_email_subject.txt
  acts_of_kindness/views.py
  happiness_app/templates/happiness_app/index.html
  happiness_project/settings.py
  post/templates/post/confirmation_emails/confirmation_email_body.txt
  post/templates/post/confirmation_emails/confirmation_email_subject.txt
  post/templates/post/post_list.html
  post/views.py
  templates/base.html
Labels: Could Have, Stephen

#125 feat: add rainbow on completed act
  acts_of_kindness/views.py
  happiness_app/templates/happiness_app/index.html
  profiles/templates/profiles/profile.html
  templates/includes/rainbow.html
Labels: Could Have, Stephen

#128 feat: add social images, titles and descriptions
  acts_of_kindness/templates/acts_of_kindness/act_detail.html
  post/templates/post/post_detail.html
  templates/base.html
Labels: Could Have, Stephen

#136 Troubleshoot emails
  post/views.py
  profiles/views.py
Labels: Could Have

#138 fix: change profile to user
  profiles/views.py
Labels: Should Have, Stephen
